spring.application.name=Api-Hub
spring.datasource.url=jdbc:mysql://localhost:3306/apihub
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true